spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

logging:
  level:
    root: WARN
    ceos.ipx: INFO
    org.hibernate.SQL: WARN
    org.springframework.security: WARN
  file:
    name: /var/log/patent/application.log

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
