spring:
  application:
    name: ipx-be

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:patent_db}
    username: ${POSTGRES_USER:ipx_postgres_user}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

server:
  port: 8080

logging:
  level:
    root: INFO
    ceos.ipx: DEBUG
    org.opensearch: WARN
    org.hibernate.SQL: DEBUG